import { ClassType } from "../types";

export const imgs = [
    "https://i.imgur.com/iYM7FP1.jpg",
    "https://i.imgur.com/vvk548x.jpg",
    "https://i.imgur.com/lMJBM3Q.jpg",
    "https://i.imgur.com/Mj7cOIA.jpg",
    "https://i.imgur.com/iYM7FP1.jpg",
    "https://i.imgur.com/3TIWqEQ.jpg",
    "https://i.imgur.com/stXuDgJ.jpg",
    "https://i.imgur.com/stXuDgJ.jpg",
    "https://i.imgur.com/DBrV6TQ.jpg",
    "https://i.imgur.com/ehdydpX.jpg",
    "https://i.imgur.com/j2FSPCA.jpg",
    "https://i.imgur.com/75BOuUS.jpg",
    "https://i.imgur.com/Qfn2NhN.jpg",
    "https://i.imgur.com/WMlBwPP.jpg",
    "https://i.imgur.com/slSFKAW.png",
    "https://i.imgur.com/FHrsKkF.jpg",
    "https://i.imgur.com/QwaDbQh.jpg",
    "https://i.imgur.com/XJR1lXo.jpg",
    "https://i.imgur.com/WU5cCsJ.jpg",
    "https://i.imgur.com/uFNxzqE.jpg",
    "https://i.imgur.com/NggdmIN.jpg",
    "https://i.imgur.com/poNlgZO.jpg",
    "https://i.imgur.com/75BOuUS.jpg",
    "https://i.imgur.com/Qfn2NhN.jpg",
    "https://i.imgur.com/ZtbyLXn.jpg",
    "https://i.imgur.com/DBrV6TQ.jpg",
    "https://i.imgur.com/ehdydpX.jpg",
    "https://i.imgur.com/kxWqCDY.jpg",
    "https://i.imgur.com/j2FSPCA.jpg",
    "https://i.imgur.com/FsgMkVV.jpg",
    "https://i.imgur.com/g1OF6Gm.jpg",
    "https://i.imgur.com/GWOQSsE.jpg",
];

export const trainers = [
    "Emily Johnson",
    "Benjamin Smith",
    "Olivia Davis",
    "Ethan Wilson",
    "Sophia Anderson",
    "Jackson Moore",
    "Ava Taylor",
    "Liam Miller",
    "Isabella Brown",
    "Noah Martinez",
    "Mia Thompson",
    "Aiden White",
    "Emma Harris",
    "Lucas Jackson",
    "Amelia Clark",
    "Oliver Turner",
    "Harper Lee",
    "Mason Garcia",
    "Abigail Wright",
    "Elijah Rodriguez",
    "Scarlett Taylor",
    "Carter Davis",
    "Grace Martinez",
    "Logan Harris",
    "Riley Smith",
    "Landon Wilson",
    "Chloe Allen",
    "Wyatt Baker",
    "Evelyn Young",
    "Samuel Lewis",
    "Zoey Johnson",
    "Henry Moore",
    "Aria Robinson",
    "Gabriel Harris",
    "Addison Taylor",
    "Daniel Miller",
    "Lily Wilson",
    "Michael Anderson",
    "Harper Lee",
    "Jack Davis",
    "Stella Martin",
    "Owen Thompson",
    "Penelope Turner",
    "Leo Clark",
    "Layla Harris",
    "Caleb Baker",
    "Aurora Young",
    "Grayson Taylor",
    "Hannah Jackson",
    "Levi Wright",
];

export const scheduleArray = [
    "Sun 9am-10am",
    "Mon 1pm-2pm",
    "Tue 10am-11am",
    "Wed 3pm-4pm",
    "Thu 2pm-3pm",
    "Fri 11am-12pm",
    "Sat 4pm-5pm",
    "Sun 2pm-3pm",
    "Mon 9am-10am",
    "Tue 5pm-6pm",
    "Wed 10am-11am",
    "Thu 1pm-2pm",
    "Fri 3pm-4pm",
    "Sat 12pm-1pm",
    "Sun 4pm-5pm",
    "Mon 11am-12pm",
    "Tue 6pm-7pm",
    "Wed 1pm-2pm",
    "Thu 4pm-5pm",
    "Fri 2pm-3pm",
    "Sat 10am-11am",
    "Sun 1pm-2pm",
    "Mon 4pm-5pm",
    "Tue 11am-12pm",
    "Wed 2pm-3pm",
    "Thu 5pm-6pm",
    "Fri 12pm-1pm",
    "Sat 3pm-4pm",
    "Sun 6pm-7pm",
    "Mon 2pm-3pm",
    "Tue 12pm-1pm",
    "Wed 4pm-5pm",
    "Thu 3pm-4pm",
    "Fri 1pm-2pm",
    "Sat 11am-12pm",
    "Sun 3pm-4pm",
    "Mon 5pm-6pm",
    "Tue 1pm-2pm",
    "Wed 11am-12pm",
    "Thu 6pm-7pm",
    "Fri 4pm-5pm",
    "Sat 1pm-2pm",
    "Sun 5pm-6pm",
    "Mon 12pm-1pm",
    "Tue 2pm-3pm",
    "Wed 5pm-6pm",
    "Thu 7pm-8pm",
    "Fri 5pm-6pm",
    "Sat 2pm-3pm",
];

export const dateStrings = [
    "20/01/2023",
    "12/04/2023",
    "05/07/2023",
    "18/09/2023",
    "22/12/2023",
    "09/02/2023",
    "14/05/2023",
    "27/08/2023",
    "03/11/2023",
    "08/01/2023",
    "16/03/2023",
    "21/06/2023",
    "29/09/2023",
    "04/12/2023",
    "17/02/2023",
    "23/05/2023",
    "10/08/2023",
    "02/10/2023",
    "11/04/2023",
    "19/07/2023",
];

export const gymClassNames = [
    "Cardio Blast",
    "Power Sculpt",
    "HIIT Fusion",
    "Yoga Flow",
    "CrossFit Challenge",
    "Spin & Sweat",
    "Zumba Party",
    "Core Crusher",
    "BodyPump Express",
    "Bootcamp Blitz",
    "Pilates Precision",
    "Kickboxing Cardio",
    "Strength Circuit",
    "DanceFit Jam",
    "TRX Total Body",
    "Barre Burn",
    "Aqua Aerobics",
    "Mindful Stretch",
    "Kettlebell Klash",
    "BoxFit Revolution",
];

export const plans = [
    {
        benefits: [
            "Basic equipment access",
            "Group fitness classes",
            "Standard gym hours",
            "Fitness assessment included",
            "Standard locker room facilities",
        ],
        price: 39,
        img: "https://i.imgur.com/WU5cCsJ.jpg",
        type: "Basic",
    },
    {
        benefits: [
            "Full equipment access",
            "Premium fitness classes",
            "Extended gym hours",
            "Personalized fitness plan",
            "Nutritional guidance included",
        ],
        price: 69,
        img: "https://i.imgur.com/OC0yaOT.jpg",
        type: "Premium",
    },
    {
        benefits: [
            "VIP equipment access",
            "Unlimited premium classes",
            "24/7 gym access",
            "Dedicated personal trainer",
            "Spa and recovery services included",
        ],
        price: 99,
        img: "https://i.imgur.com/WMlBwPP.jpg",
        type: "VIP",
    },
];
